name: Integration Tests

on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]
  
  
jobs:
  run_cypress:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          config-file: cypress.json
          wait-on: http://localhost:3000
          wait-on-timeout: 300
          browser: chrome
          headless: true
          spec: '**/url-decoder/**/*.spec.js'
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}